name: customer_analytics_api
description: An api for customer engagement and revenue analytics, enabling marketing and sales insights.
version: 0.0.1
auth:
  heimdallUrl: https://dataos-training.dataos.app/heimdall
  userGroups:
    - name : datadev
      description: data dev group
      includes:
        - users:id:manishagrawal
        - users:id:sanduvenkatasujatha
        - users:id:aadityasoni

    - name: default
      description: Default group to accept everyone
      includes: "*"
logLevel: 'DEBUG' 
cachePath: tmp
sources:
  - name: lens # profile name
    type: lens
    lensName: 'public:customer360'

metrics:
  type: summary
  percentiles: [ 0.5, 0.75, 0.95, 0.98, 0.99 ]
